package genericos.logica;

public class Caja<T> {

    private T contenido;

    public void ponerAlgo(T contenido) {
        this.contenido = contenido;
    }

    public T obtenerAlgo() {
        return contenido;
    }
}

/*
EN ESTE EJEMPLO SE TIENE UNA CAJA, Y QUIERO GUARDAR VARIOS TIPOS DE COSAS EN LA CAJA, REUTILIZANDO LA CLASE LAS VECES QUE QUERAMOS

ESTO ANTERIORMENTE NO SE PODRIA HACER, YA QUE SOLO PODEMOS GUARDAR COSAS DE UN SOLO TIPO
POR ESO CREAMOS CLASE CAJA, Y COMO PARAMETROS ESTABLECEMOS QUE PUEDE RECIBIR UN TIPO DE DATO GENERICO T

EL ATRIBUTO SERA DEL TIPO GENERICO T, Y SE GUARDARA UN CONTENIDO

EL METODO PONERALGO RECIBIRA UN PARAMETRO DEL TIPO GENERICO T, Y SE GUARDARA EN EL ATRIBUTO CONTENIDO

YO PODRE DETERMINAR QUE TIPO DE DATO GUARDAR EN LA CAJA, Y QUE TIPO DE DATO OBTENER DE LA CAJA



 */